// Array of products, each product is an object with different fieldset

var products = [
  {
    name: "Cereal bar",
    halal: true,
    containsNuts: true,
    lactose: true,
    organic: true,
    price: 2.99,
    quantity: 0,
  },
  {
    name: "Eggs",
    halal: true,
    containsNuts: false,
    lactose: false,
    organic: true,
    price: 9.99,
    quantity: 0,
  },
  {
    name: "Pasta",
    halal: true,
    containsNuts: false,
    lactose: false,
    organic: false,
    price: 5.49,
    quantity: 0,
  },
  {
    name: "Snickers chocolate bar",
    halal: true,
    containsNuts: true,
    lactose: true,
    organic: false,
    price: 1.49,
    quantity: 0,
  },
  {
    name: "Box of strawberries",
    halal: true,
    containsNuts: false,
    lactose: false,
    organic: true,
    price: 4.99,
    quantity: 0,
  },
  {
    name: "Brie cheese",
    halal: true,
    containsNuts: false,
    lactose: true,
    organic: false,
    price: 14.99,
    quantity: 0,
  },
  {
    name: "Greek yogurt",
    halal: true,
    containsNuts: false,
    lactose: true,
    organic: true,
    price: 5.99,
    quantity: 0,
  },
  {
    name: "Bag of milk",
    halal: true,
    containsNuts: false,
    lactose: true,
    organic: false,
    price: 3.79,
    quantity: 0,
  },
  {
    name: "Canned tomatoes",
    halal: true,
    containsNuts: false,
    lactose: false,
    organic: true,
    price: 6.59,
    quantity: 0,
  },
  {
    name: "Bag of walnuts",
    halal: true,
    containsNuts: true,
    lactose: false,
    organic: true,
    price: 0.79,
    quantity: 0,
  },
  {
    name: "Pepperoni pizza",
    halal: false,
    containsNuts: false,
    lactose: true,
    organic: false,
    price: 24.99,
    quantity: 0,
  },
  {
    name: "Dogfood",
    halal: false,
    containsNuts: false,
    lactose: false,
    organic: true,
    price: 12.99,
    quantity: 0,
  },
  {
    name: "Chicken",
    halal: true,
    containsNuts: false,
    lactose: false,
    organic: false,
    price: 16.99,
    quantity: 0,
  },
  {
    name: "Pork",
    halal: false,
    containsNuts: false,
    lactose: false,
    organic: false,
    price: 19.99,
    quantity: 0,
  },
  {
    name: "Frosted Flakes Cereal",
    halal: true,
    containsNuts: true,
    lactose: false,
    organic: true,
    price: 11.99,
    quantity: 0,
  },
  {
    name: "Polar Ice Vodka",
    halal: false,
    containsNuts: false,
    lactose: false,
    organic: false,
    price: 49.99,
    quantity: 0,
  },
];
